version: '3.9'
services:
  frontend:
    build: ./client
    ports:
      - '80:80'
    environment:
      - PORT=80
      - API_URL=http://host.docker.internal:5000
    container_name: frontend
    restart: always
  backend:
    build: ./server
    ports:
      - '5000:5000'
    container_name: backend
    restart: always
